#!/bin/sh

REPOS="$1" # repository path
REV="$2" # revision number
SVNLOOK="/opt/CollabNet_Subversion/bin/svnlook" # svnlook path
AUTHOR=$($SVNLOOK author "$REPOS" -r "$REV") # To get the author name who does the check-in

# To and From mail addresses
#TO="dhanush-sw@inedasystems.com" # who will receive the notifications 
#TO="socplatform-qa@inedasystems.com" # who will receive the notifications
#FROM="nagoorsaheb.inaganti@incubesol.com" # what will be in "FROM" fields

TO="vinaykumar.medari@incubesol.com" # who will receive the notifications
FROM="vinaykumar.medari@incubesol.com" # what will be in "FROM" fields

# svnnotify, which will take care of sending the email based on the options provided
svnnotify \
        --repos-path "$REPOS" \
        --revision "$REV" \
        --to $TO \
        --from $FROM \
	--svnlook $SVNLOOK \
	--attach-diff true \
	--subject-prefix "SVN-Check-in is done by the user - $AUTHOR with revision - " \
	--no-first-line \
	--header "Check-in details of revison:$REV on the repository:$REPOS 
	are included in this mail. For more clear details about changes please check the attached log file." \
       --handler HTML::ColorDiff \ # make diff pretty
        --subject-cx "check-in Notification mail"\# include additional info in the subject
	2>&1 &


URL=`$SVNLOOK changed "$1"`;
var1=$(echo $URL | cut -f1 -d' ');
var2=$(echo $URL | cut -f2 -d' ');

declare -a Array=($(echo $var2 |cut -d'/' --output-delimiter=" " -f1-))

length=${#Array[@]};

exec >> /tmp/post-commit.log 2>&1
echo "$REPOS";
echo "$var2";
echo "${Array[1]}";



# The below line of code is to trigger the auto build in the build server for each check-in
sshpass -p "Welcome123" ssh -t -t socplatform-qa@192.168.42.46 perl Desktop/post-commit/select_build.pl ${Array[1]} >& /dev/null &

exit 0
