#!/usr/bin/perl
#test check-in
#**********************************************************************
# 
# File name: pre-commit
# 
# Location: 'hooks' directory of a repository for which we want to
#           restrict the user to enter the check-in log detailsin 
#           the SVN server 
# 
# Description: This script will run in the SVN server when a developer
#              tries to do check-in
#
#**********************************************************************

#Declaration of Destination path

$svnlook = 'ltools/SVN/CollabNetSubversion-client-1.6.5-2/bin/svnlook'; 
$matched=0;

$repos = $ARGV[0]; 
$txn = $ARGV[1]; 
$comment = `$svnlook log -t "$txn" "$repos"`; 
$dirs_changed=`$svnlook dirs-changed -t "$txn" "$repos"`;

@dirs=split('\n',$dirs_changed);

foreach $a (@dirs)
{
	if($a =~/Advanced/)
	{
		$matched=1;
		last;
	}
	if($a =~/Micro/)
	{
		$matched=1;
		last;
	}
	if($a =~/Tags/)
	{
		$matched=1;
		last;
	}
	if($a =~/Branches/)
	{
		$matched=1;
		last;
	}
	if($a =~/Experimental/i)
	{
		$matched=1;
		last;
	}
	if($a =~/doc/i)
	{
		$matched=1;
		last;
	}
}

$len = length($comment);

if($len == 1)
{ 
  print STDERR "A comment is required"; 
  exit(1); 
}
elsif($comment=~/(.+)/)
{
	if($comment=~/(.+)\n(.+)\n/i)
	{
		$IssueId = $1;
		$IssueType = $2;

		if(!($IssueType =~ /^Issue Type:\s*(Bug|Feature|Enhancement|Other)\s*$/i))
		{
			#print STDERR "Issue Type is not entered in the below format\n Issue Type: <Bug|Feature|Enhancement|Other>";
			if($matched eq 0)
			{
				print STDERR "SVN commit has blocked..\n";
				exit(1);
			}
		}
	}
	else
	{
		if($matched eq 0)
		{
			print STDERR "SVN commit has blocked..\n";
			exit(1);
		}
	}
}
else
{
	exit(0);
}

exit(0);

